#pragma once

#include <stdint.h>

/*
 * This is a simplified version of the ContractTree,
 * using c-native types.
 * This representation is generated by the instrumentation pass
 * for use with dynamic tools.
 */

struct Tag_t {
    const char* tag;
    int64_t param;
    bool operator<(const Tag_t other) const { return tag < other.tag && param < other.param;}
};

struct TagsMap_t {
    void** functions; // List of function pointers
    Tag_t* tags; // List of tags (matching above funcptr)
    int64_t count;
};

// Number must match those defined in ContractTree.hpp!
enum ParamAccess : int32_t { NORMAL = 0, DEREF = 1, ADDROF = 2 };
struct CallParam_t {
    int32_t callP;
    bool callPisTagVar; // Read as bool
    int32_t contrP;
    ParamAccess accType;
};
enum Comparator : int32_t { NEQ, GT, GTEQ, LT, LTEQ, EXEQ };

struct RWOp_t {
    int32_t idx;
    ParamAccess accType;
    bool isWrite;
};
struct CallOp_t {
    const char* function_name;
    CallParam_t* params;
    int32_t num_params;
    void* target_function;
};
struct CallTagOp_t {
    const char* target_tag;
    CallParam_t* params;
    int32_t num_params;
};
struct ReleaseOp_t {
    void** release_op;
    int32_t release_op_kind;
    void** forbidden_op;
    int32_t forbidden_op_kind;
};
struct ParamReq_t {
    const Comparator comparator;
    const void* value;
};
struct ParamOp_t {
    const int32_t idx;
    const ParamReq_t* requirements;
    const int32_t num_reqs;
};

// Number must match those defined in enums in ContractTree.hpp (operation + connective)!
enum ContractConnective : int32_t {
    // Connectives
    AND,
    OR,
    XOR,
    // Operations
    UNARY_READ,
    UNARY_WRITE,
    UNARY_ALLOC,
    UNARY_CALL,
    UNARY_CALLTAG,
    UNARY_RELEASE,
    UNARY_PARAM
};
struct ContractFormula_t {
    ContractFormula_t* children;
    int32_t num_children;
    ContractConnective conn;
    const char* msg;
    void** data; // Only filled if conn == UNARY. Pointer to corresponding operation struct.
};

struct Contract_t {
    ContractFormula_t* precondition;
    ContractFormula_t* postcondition;
    void* function;
    const char* function_name;
};

struct Reference_t {
    const char* ref;
    const char* type;
};

struct ContractDB_t {
    Contract_t* contracts;
    int32_t num_contracts;
    TagsMap_t tagMap;
    Reference_t* references;
    int32_t num_references;
};

#ifdef __cplusplus
extern "C" {
#endif

// Callback function declarations
void PPDCV_Initialize(int32_t* argc, char*** argv, ContractDB_t const* DB);
void PPDCV_FunctionCallback(bool isRel, void* function, int32_t num_params, ...); // relevancy, funcptr, num params, then sizeof param and param each
void PPDCV_MemRCallback(bool const isRel, void const* buf);
void PPDCV_MemWCallback(bool const isRel, void const* buf);

#ifdef __cplusplus
}
#endif
